### ISSUE TITLE
データベース

### ISSUE THREAD

**Issue by qiugits** [qiugits/VirtualRefrigerator#1]
Assign to: @s161 

データベースでExcelを取り込む
今の課題点：Excelが読めない→上の行を無視してやってみる
→SQLのファイルに変換する

（→MySQLにテーブルを追加で取り込める方法）

**Comment by qiugits** [comment]
ちょっとググった感じ、CSVを扱うのが良さげかも

参考：
- https://qiita.com/hkengo/items/59ba599ef48c613f2402
- http://melborne.github.io/2013/01/24/csv-table-method-is-awesome/

なので、
1. Excelを不要な行を手動で取り除いて、カラム名は何もしない状態の7行目だけ残す。「ー」になってるのはいい名前つける（かぶらなければOK）
2. 手動でCSVファイルに直す。ここまでは手動だが作業量多くないはず。
3. CSVとしてrubyに読ませる
4. よしなに処理してSQLへ
という流れかな。

3.まではできるはずなのでやってみて、出来たor出来ないを知らせて欲しいです。

**Comment by s161** [comment]
3までは出来ました。

**Comment by qiugits** [comment]
@s161 ナイス！

そしたら、SQLは後にしよう。
まずは整形してCSVファイルに保存することをゴールとしよう。

なので、読ませたCSVオブジェクトに対して
- 例外の処理を施す（`-`, `(0)`, `Tr`などの数字以外を処理して数字にする）
- 処理された整形済みのデータをCSVに保存する

ここまでを来週までにできるといいなーと。

余裕があれば
- 5大栄養素に計算する
- それを新たなカラムとしてCSVに保存できるように更新する
までできるとサイコー。

**Comment by qiugits** [comment]
素晴らしい
