### ISSUE TITLE
HTMLとCSS

### ISSUE THREAD

**Issue by qiugits** [qiugits/VirtualRefrigerator#3]
Assigned to: @lmn8cs 

現状：デザインまである程度考えた

HTMLはバックエンドの方がまだできてないので、ハードコーディングしてもらって
HTMLとCSSの設計をしてもらう
static-pages/ とかでやってもらってOK

**Comment by lmn8cs** [comment]
HTMLを先に作ります

**Comment by qiugits** [comment]
HTMLのページをハードコーディングで作って見る
CSSは余裕があったら

**Comment by qiugits** [comment]
閉じた冷蔵庫
開いた冷蔵庫
入れるページ
出すページ

**Comment by qiugits** [comment]
@lmn8cs 
今日最後に言った通りHTMLの4ぺーじ作ってみてください。
そこまで出来たら知らせてください。
